### ISSUE TITLE
Update macro DSL to support any key and multiple keypresses

### ISSUE THREAD

**Issue by scott181182** [scott181182/Macrobot#30]
Implement the following grammar for key commands:
```
<key-command> ::= <key word> ( "+" <key-word> )* ( " " <key-command> )?
<key word> ::= <named-key> | <lock-key> | <ext-key> | <arrow-key> | <function-key> | <char-key>
<named-key> ::=("esc" | "escape") | "tab" | "shift" | "ctrl" | "meta" | "alt" | "enter" | "space" | "backspace" | ("fn" | "function")
<lock-key> ::= "capslock" | "numlock" | "scrolllock"
<ext-key> ::= ("del" | "delete") | ("ins" | "insert") | "home" | "end" | ("pgup" | "pageup") | ("pgdown" | "pagedown")
<arrow-key> ::= ("up" | "arrowup") | ("down" | "arrowdown") | ("left" | "arrowleft") | ("right" | "arrowright")
<function-key> ::= "f1" | "f2" | "f3" | "f4" | "f5" | "f6" | "f7" | "f8" | "f9" | "f10" | "f11" | "f12"
<char-key> ::= [a-z0-9`'=[];,.] | "/" | "\" | "-"
```
*NOTE*: the `"fn"` key word is NOT for the numerical function keys covered in`<function-key>`, but rather for the modifier key used on some systems expand the range of operations a single key can perform.

`<key-command>` can be one or more space-delimited `<key-command>`s

A single key command should emulate the keys being pressed in the same order as listed, and then released in the opposite order.
Multiple key commands (separated by spaces) should be executed in the order listed.

Example commands:
```
n
shift+m
tab
capslock
ctrl+alt+delete
ctrl+shift+n ctrl+t
h e l l o , space w o r l d shift+1
```

The compromise in this DSL is that you can't just send shifted characters, like "!" or "+", instead requiring "shift+1" and "shift+=" respectively. This can expand the flexibility of the DSL itself, however, with future key commands involving double quotes or other shifted characters.

**Comment by WugWugg** [comment]
I'm not too sure if the "fn" key as described is accessible by software as it usually changes hardware settings. Enigo doesn't have this key listed as well.

---

Using space-delimiters for key-command groups will keep each key-command atomic, but I see problems on the horizon. On one hand you only mentioned the characters created by pressing the shift key being "reserved". But on the other this feels like any character created by pressing any modifier key. I think a cool feature is that we can send any unicode character and this might set us down a path where alt-codes are the only way to send those. _Which alt-codes themselves would be a tricky thing to represent in and of themselves due to the nature of needing to hold the alt but sequentially "click" the other keys._

The way I approach this is to treat every group of text separated by a space as an atomic thing. Then, to allow for the expanded flexibility we use, what I would like to call, "functions" to provide it. These would be treated much like the "shift" or "ctrl" identifiers but instead of mapping the string to a key it would map the string to a nuanced behavior the DSL. This might looks something like: `hold_first:alt+1+6+4` giving the result of `ñ`.

So alt codes are a moot point, but here are a few other ideas:
| Key-Command | Output |
| ------------- | ------------- |
| `type:Hello+World!`  | `Hello, World!` |
| `down:u delay:250 up:u`  | `uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu` (250ms worth of u's) |
| `range:1..3 repeat:3+😎` | `123 😎😎😎` |

I think this would offer better ergonomics at the surface level but still allow this DSL to go deeper and, hopefully, be more readable.

**Comment by scott181182** [comment]
@DarkWugWug Based on out-of-band conversations, we can remove support for the function modifier due to limitation of our user input emulation library, but otherwise keep this grammar as version 2.1, and open an issue closer to your proposal as v3 when we implement a context-free parser?

**Comment by scott181182** [comment]
Also found issue #33
